INSERT INTO FARM(NAME) VALUES('Georges Farm');
INSERT INTO FARM(NAME) VALUES('Happy Farm');

INSERT INTO FIELD (FARM_ID, NAME) VALUES((SELECT ID FROM FARM WHERE NAME = 'Georges Farm'), 'Field North');

